### ISSUE TITLE
Kustomize replacements cannot handle all use cases of vars

### ISSUE THREAD

**Issue by pbecotte** [kubernetes-sigs/cli-experimental#198]
Went to read the docs on vars today, and see that most of them have been replaced with discussion of a new transformer. Which is great, but it doesn't actually work for the use cases I use vars for today. Lets consider the given example-

`args: ["-c", "echo $(WORDPRESS_SERVICE); echo $(MYSQL_SERVICE)"]`

They then go on to explain how to replace the var with replacements... just change the input like so...

`args: ["-c", "echo", "WORDPRESS_SERVICE", ";", "echo", "MYSQL_SERVICE"]`

```
replacements:
- source: 
    name: demo-wordpress
    kind: Service
    version: v1
  targets:
  - select: 
      kind: Deployment
      name: demo-wordpress
    fieldPaths:
    - spec.template.spec.initContainers.[name=init-command].args.2
```
But here's the problem... the change in the `args` field BREAKS the job! These are not equivalent!

`bash -c "echo hello; echo world"` and `bash -c echo hello ; echo world`

The reason they changed it is because the API as is fundamentally offers no way to approach this problem. Sometimes you need to insert a var-ref or replacement in the middle of another string. In lots of cases, replacing a whole field is great, but in others its not.
You can see some thought WAS put into it with the `delimiter` and `index` pair. The system supports `/replace/this/value/$here/` which satisfies a lot of use cases. But consider a kustomization base that includes a configmap. It has 100 lines of ini text. In your leaf kustomiztions you want to patch out one specific value from that huge string (maybe the LDAP group in a dex config, for example). Var is the only way to do that, or copy/paste the whole 100 lines into every leaf project.
