### ISSUE TITLE
secretGenerator missing literal example

### ISSUE THREAD

**Issue by exocode** [kubernetes-sigs/cli-experimental#221]
I was looking for an literal example for secretGenerator at this page: https://kubectl.docs.kubernetes.io/references/kustomize/secretgenerator/

Maybe that snippet could be added to the docs.. 

```yaml
secretGenerator:
  - name: my-secrets
    literals:
      - my_literal="myvalue"
```
