### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by aperepel** [kubernetes-sigs/cli-experimental#229]
https://kubectl.docs.kubernetes.io/references/kustomize/replicas/

The following block has a typo in the `container` at the bottom:
```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 5
  template:
    containers:
      - name: the-container
        image: registry/conatiner:latest # typo here
```

Edit page doesn't work either, will file an issue
