### ISSUE TITLE
Problem with transformation from vars to replacements

### ISSUE THREAD

**Issue by bomc** [kubernetes-sigs/cli-experimental#285]
I use Kustomize and would like to migrate to Replacements. I use vars for replacing variables in simple yaml files or in parts of bash scripts. It works as expected. An example is given below. The simple my-config.yaml is after building the part of the ConfigMap and the variable was replaced.

**kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: my-config-yaml
    behavior: create
    envs:
    - ./my-config.param
    files:
      - ./my-config.yaml
generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: MY_VARIABLE
    objref:
      kind: ConfigMap
      name: my-config-yaml
      apiVersion: v1
    fieldref:
      fieldpath: data.MY_VARIABLE

configurations:
  - ./params.yaml
```

**my-config.yaml** is after build part of the configMap and '$(MY_VARIABLE)' is replaced with 'replace', see output below. 
```
my.variable.to.replace: $(MY_VARIABLE)
```

**params.yaml**
```
varReference:
  - path: data/my-config.yaml
    kind: ConfigMap
```

**my-config.param**
```
MY_VARIABLE=replace
```

**Output as expected:**
```
apiVersion: v1
data:
  MY_VARIABLE: replace
  my-config.yaml: |
    my.variable.to.replace: replace
kind: ConfigMap
metadata:
  name: my-config-yaml
```

Is it possible to implement this use case with replacements or what alternatives are there?
