### ISSUE TITLE
configMapGenerator missing doc about environment variables expanded into for env files

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/cli-experimental#303]
On this page https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-env-file

It mentions that the file like `tracing.env` will contain each line with a key value pair separated by `=`

But it doesn't mentions that `tracing.env` can just contain keys, and the values be declare as environment variables

For example

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: tracing-options
  envs:
  - tracing.env
```

Declare values as environment variables
```
export ENABLE_TRACING=true
export SAMPLER_TYPE=probabilistic
export SAMPLER_PARAMETERS=0.1
```

```
# tracing.env
ENABLE_TRACING
SAMPLER_TYPE
SAMPLER_PARAMETERS
```

Output
```
apiVersion: v1
kind: ConfigMap
metadata:
  # The name has had a suffix applied
  name: tracing-options-6bh8gkdf7k
# The data has been populated from each literal pair
data:
  ENABLE_TRACING: "true"
  SAMPLER_TYPE: "probabilistic"
  SAMPLER_PARAMETERS: "0.1"
```
