### ISSUE TITLE
Replacement can't select sources existing in the cluster.

### ISSUE THREAD

**Issue by EmielFerment** [kubernetes-sigs/cli-experimental#335]
In a namespace we have two secrets, i.e. test and production. 

When trying to refer to the secret using replacement kustomize does not seems to find the secret.

kustomization.yml:
```
- source:
    version: v1
    kind: Secret
    name: database-credentials-test    
    namespace: eems-lng
```
result:
`error: nothing selected by Secret.v1.[noGrp]/database-credentials-test.eems-lng`

Is this by design or do I do something wrong?

Regards,
Emiel
