### ISSUE TITLE
Wrong example deployment.yaml file in apply docs

### ISSUE THREAD

**Issue by kklis** [kubernetes-sigs/cli-experimental#377]
The example file on https://kubectl.docs.kubernetes.io/references/kubectl/apply/ does not work, and 'kubectl apply -f deployment.yaml` ends with decoding error:
```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 5
  template:
    containers:
      - name: the-container
        image: registry/container:latest
```
There should be additional `spec:` under `template` for the deployment to work.
