### ISSUE TITLE
A typo in namePrefix document example?

### ISSUE THREAD

**Issue by jaroslawhartman** [kubernetes-sigs/cli-experimental#73]
There is a small typo in the example [doc](https://kubectl.docs.kubernetes.io/references/kustomize/nameprefix/):

# Example
## File Input

```
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 5
  template:
    containers:
      - name: the-container
        image: registry/conatiner:latest
```

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: overlook-

resources:
- deployment.yaml
```

## Build Output
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alices-the-deployment
spec:
  replicas: 5
  template:
    containers:
    - image: registry/conatiner:latest
      name: the-container
```

Build output should have name `overlook-the-deployment`, not `alices-the-deployment`
